; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "Amju Piano Fest"
#define MyAppVersion "0.4"
#define MyAppPublisher "Amju Games"
#define MyAppURL "https://www.amju.com/"
#define MyAppExeName "amju_piano_fest.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]

; juliet - Piano Fest is now 64 bit!
SetupArchitecture=x64

; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DE8E248C-DC5E-43A0-8840-7A34015A2C80}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=..\..\Build\WindowsInstaller
OutputBaseFilename=amju_piano_fest_installer
SolidCompression=yes
WizardStyle=modern dynamic

; Juliet - add images. TODO Create custom images
DisableWelcomePage=no
; Large image on the left (Recommended size: 240x459 or larger for high-DPI)
WizardImageFile=..\..\Assets\Windows\logo-512.png

; Small image in the top right (Recommended size: 147x147 or larger)
WizardSmallImageFile=..\..\Assets\Windows\logo-256.png

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\Build\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\Build\CompiledAssets\data-WIN.glue"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\Build\CompiledAssets\music-WIN.glue"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

; BASS DLLs
Source: "..\..\..\amjulib\3rdPartyLibs\Bass\2.4.18.3\bass24-win\x64\bass.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\..\amjulib\3rdPartyLibs\Bass\BassMidi\2.4.15.3\bassmidi24-win\x64\bassmidi.dll"; DestDir: "{app}"; Flags: ignoreversion

; BugSplat binaries
Source: "..\..\..\amjulib\3rdPartyLibs\BugSplat\Windows\x64\Release\bin\BugSplatMonitor.exe"; DestDir: "{app}"; Flags: ignoreversion
; We aren't setting the required registry key for this.
;Source: "..\..\..\amjulib\3rdPartyLibs\BugSplat\Windows\x64\Release\bin\BugSplatWer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\..\amjulib\3rdPartyLibs\BugSplat\Windows\x64\Release\bin\BugSplatRc.dll"; DestDir: "{app}"; Flags: ignoreversion
; MS redistributables, also required by BugSplat.
Source: "..\..\..\amjulib\3rdPartyLibs\BugSplat\Windows\Redist_DLLs\*.dll"; DestDir: "{app}"; Flags: ignoreversion


[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

