; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "Amju Piano Fest"
#define MyAppVersion "0.4"
#define MyAppPublisher "Amju Games"
#define MyAppURL "https://www.amju.com/"
#define MyAppExeName "amju_piano_fest.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3D4ACA7D-9958-4524-AC82-BE6E1725268B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\Juliet\repos\amt\music-theory\Build\WindowsInstaller
OutputBaseFilename=amju_piano_fest_installer
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Juliet\repos\amt\music-theory\Build\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Juliet\repos\amt\music-theory\Build\Release\bass.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Juliet\repos\amt\music-theory\Build\Release\bassmidi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Juliet\repos\amt\music-theory\Build\Release\glut32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Juliet\repos\amt\music-theory\Build\CompiledAssets\data-WIN.glue"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Juliet\repos\amt\music-theory\Build\CompiledAssets\music-WIN.glue"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

