#include <CommandLineArgs.h>
#include "AutoTest.h"
#include "GS3dExample.h" // for dev/test of 3d scene
#include "GS3dTitle.h"
#include "GSAnimals.h"
#include "GSHero.h"
#include "GSPlayNotes.h" // --keyboard mode
#include "GSShowGui.h" // for quick dev/test of a new GUI
#include "GSTestShowScore.h"
#include "GSVerify.h" // check music assets at start
#include "InitialState.h"

namespace Amju
{
void SetInitialState()
{
  const auto& args = GetCommandLineArgs();

  auto game = TheGame::Instance();

  if (args.Contains("--viewscore"))
  {
    // Show a score, generated by juliet_musicxml or MakeScore 
    game->SetCurrentState(TheGSTestShowScore::Instance());
    return;
  }

  if (args.Contains("--keyboard"))
  {
    // Show a playable piano keyboard
    game->SetCurrentState(TheGSPlayNotes::Instance());
    return;
  }

  if (args.Contains("--3d"))
  {
    // Show a 3d scene; the scene filename should be the 3rd command-line param.
    game->SetCurrentState(TheGS3dExample::Instance());
    return;
  }

  if (args.Contains("--animals"))
  {
    // Animals test state
    game->SetCurrentState(TheGSAnimals::Instance());
    return;
  }

  if (args.Contains("--hero"))
  {
    // Go directly to Hero mode
    game->SetCurrentState(TheGSHero::Instance());
    return;
  }

  if (args.Contains("--gui"))
  {
    // Show a GUI, the gui filename is the 3rd command-line param.
    game->SetCurrentState(TheGSShowGui::Instance());
    return;
  }

#ifdef _DEBUG
  game->SetCurrentState(TheGSVerify::Instance());
#else
  // In release mode, skip Verify state, unless we are in 
  //  auto-test mode.
  if (GetAutoTestLevel() == AutoTestLevel::AMJU_NO_TEST)
  {
    // Skip verify
    game->SetCurrentState(TheGS3dTitle::Instance());
  }
  else
  {
    game->SetCurrentState(TheGSVerify::Instance());
  }
#endif
}
}

