#include <CommandLineArgs.h>
#include "GS3dExample.h" // for dev/test of 3d scene
#include "GS3dTitle.h"
#include "GSAnimals.h"
#include "GSHero.h"
#include "GSPlayNotes.h" // --keyboard mode
#include "GSShowGui.h" // for quick dev/test of a new GUI
#include "GSTestShowScore.h"
#include "GSVerify.h" // check music assets at start
#include "InitialState.h"

namespace Amju
{
void SetInitialState()
{
  const auto& args = GetCommandLineArgs();

  if (args.Contains("--viewscore"))
  {
    // Show a score, generated by juliet_musicxml or MakeScore 
    TheGame::Instance()->SetCurrentState(TheGSTestShowScore::Instance());
    return;
  }

  if (args.Contains("--keyboard"))
  {
    // Show a playable piano keyboard
    TheGame::Instance()->SetCurrentState(TheGSPlayNotes::Instance());
    return;
  }

  if (args.Contains("--3d"))
  {
    // Show a 3d scene; the scene filename should be the 3rd command-line param.
    TheGame::Instance()->SetCurrentState(TheGS3dExample::Instance());
    return;
  }

  if (args.Contains("--animals"))
  {
    // Animals test state
    TheGame::Instance()->SetCurrentState(TheGSAnimals::Instance());
    return;
  }

  if (args.Contains("--hero"))
  {
    // Go directly to Hero mode
    TheGame::Instance()->SetCurrentState(TheGSHero::Instance());
    return;
  }

  if (args.Contains("--gui"))
  {
    // Show a GUI, the gui filename is the 3rd command-line param.
    TheGame::Instance()->SetCurrentState(TheGSShowGui::Instance());
    return;
  }

#ifdef _DEBUG
  TheGame::Instance()->SetCurrentState(TheGSVerify::Instance());
#else
  TheGame::Instance()->SetCurrentState(TheGS3dTitle::Instance());
#endif
}
}

