// * Amjula music theory *
// (c) Copyright 2024 Juliet Colman

#pragma once

#include <vector>
#include <MessageQueue.h>

namespace Amju
{
// TODO Wrong place for this.
// Compare two MIDI note pitches. Return true if the player
//  note is correct wrt the note on the score.
// We can ignore octave to make this easier, or be strict
//  depending on difficulty.
bool IsPlayerPitchCorrect(int playerNote, int scoreNote);

// Player Music Keyboard Event.
// This could be generated by:
// 1. a mouse/finger up or down on a virtual key on the GuiMusicKb
// 2. a key up or down event, for qwerty keyboard control
// 3. a MIDI note event from a connected device.
struct MusicKbEvent 
{
  MusicKbEvent() = default;
  MusicKbEvent(int note, bool on) : m_note(note), m_velocity(on ? 127 : 0) {}
  MusicKbEvent(int note, int velocity) : m_note(note), m_velocity(velocity) {}

  bool IsOn() const { return m_velocity > 0; }
 
  int m_note = 0;
  int m_velocity = 0;
};

// Function called when the MessageQueue processes a MusicKbEvent.
// This function passes the event on to the currently active GameState,
//  (all game-specific states are derived from GSBase and know 
//   about this event type.)
void OnMusicKbEvent(const MusicKbEvent&);

// MessageQueue message wrapping a MusicKbEvent so we can add them
//  to the message queue. 
// TODO Not sure why we need both types, keep it like this for now.
struct MusicKbMsg : public Message
{
  // Construct a MessageQueue message from a music event.
  MusicKbMsg(const MusicKbEvent& e) : m_event(e) {}

  // Call the above callback when it's time to execute this message.
  virtual void Execute() override
  {
    OnMusicKbEvent(m_event);
  }

  // The event we are wrapping.
  MusicKbEvent m_event;
};

using MusicMessages = std::vector<RCPtr<MusicKbMsg>>;
}

